# Generated by Django 2.1.2 on 2018-10-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='가격'),
        ),
    ]
