import numpy as np

data = np.loadtxt('./day15/ex2.csv', delimiter=',', dtype=np.int)
print(data[:3, 0:3])
print('-' * 20)
print(data.shape)
print('-' * 20)
print(np.unique(data[:, 1]))
print('-' * 20)
print('부산:', data[data[:, 1] == 8] )
print('-' * 20)
print('전국 합계:', np.sum(data[:, 2]))
print('-' * 20)
print('가장 낮은 증감률:', np.min(data[:, 5]))
print('-' * 20)
print('400이상 발생건수:', data[data[:, 2] >= 400])